version: '3.8'

services:
  webapp:
    container_name: webapp
    hostname: webapp
    build: ./webapp
    environment:
      APP_DB_NAME: ${POSTGRES_DB}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
      APP_DB_HOST: db
    networks:
      - internal_network
    volumes:
      - webapp_data:/usr/src/app
    depends_on:
      - db # Ensure postgres starts first
    restart: always

  db:
    container_name: db
    hostname: db # this must be changed to correspond to the hostname the webapp specifies...
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal_network
    volumes:
      - postgres_data:/var/lib/postgresql/app
    restart: always

  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx config (mounted as read-only)
    depends_on:
      - webapp # Ensure webapp starts first
    restart: always

networks:
  internal_network:
    driver: bridge
    internal: true
  external_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  webapp_data:
    driver: local
